### ISSUE TITLE
Metadata editing - UX brief

### ISSUE THREAD

**Issue by aswallace** [AllenInstitute/biofile-finder#120]
This is the UX ticket corresponding to #96 

## Description
From the app page, we want to provide a pop-up modal that allows users to edit the metadata stored in MMS for single or multiple selected files -- but currently **only for internal data sources (AICS FMS)**. The changes would overwrite existing metadata for those files in MMS. This feature would be available on right click in the context menu as an "Edit Metadata" option.

_Type of UX work needed_: 
Currently primarily research? But designs would also be greatly appreciated

_Problem(s) to solve_:
   - Some fields will not be directly editable by the user. This is because some fields are not stored in MMS itself, but rather inferred from other fields and/or retrieved from Labkey/other sources (e.g., plate barcode vs solution)
   - Our current understanding of the use case is that it would mainly be for editing many (e.g., 200) files at once for a single typo that should be updated to the same value in all 200 files, rather than many changes in a single file or many different values for different files. However, it's possible that users aren't coming to us for single file or many valued changes (may not feel comfortable asking for these), so we may have a limited understanding of the demand for those use cases.
   - We can't guarantee that all files selected by the user will have values for the attribute they want to edit, or that the values they do have will be the same
   - We're currently referencing the File Upload App mass editing UI, which only displays a single row that will update values for all selected files, and does not present the current values for the selected files. We're unsure how much we should emulate that interface

## Size estimate
_Effort level (xs, sm, m, lg, xl). Timeframe/due date for UX deliverables?_
Original timeframe was over the summer, but we're happy to wait for research

## Scope
_What will we do? What will we NOT do?_

## User needs statement(s)
_As a [type of user], I need/want to [action(s)], so that I can [goal]._

Dev assumptions:
- As a researcher, I want to select and edit (multiple) file(s), so that I can correct typos in file metadata.
- As a researcher, I want to select and edit (multiple) file(s), so that I can **add** an attribute field to the file(s).
   - ...I want to add an **existing** (FMS) attribute to the file(s)?
   - ...I want to **create a new** attribute and add it to the file(s)?
- As a researcher/developer, I want to edit many files at once, so that I can make a consistent change across all of them
- As a researcher, I want to edit files that were uploaded by someone other than me (not allowed on FUA), especially from someone who has left the institute

## Additional notes
_Knowns/unknowns, stakeholders, time/dependency considerations, deliverables_
Names of folks who've recently requested editing: Antoine B, Sara C, Filip

**Comment by lynwilhelm** [comment]
- Some fields will not be editable by the user because some fields are not stored in MMS itself, but rather inferred from other fields and/or retrieved from Labkey/other sources (e.g., plate barcode vs solution) 
**Would be helpful to show even fields that aren’t editable and to show origin of data**
- Our current understanding of the use case is that it would mainly be for editing many (e.g., 200) files at once for a single typo that should be updated to the same value in all 200 files, rather than many changes in a single file or many different values for different files. However, it's possible that users aren't coming to us for single file or many valued changes (may not feel comfortable asking for these), so we may have a limited understanding of the demand for those use cases. 
**Seems like only one small change to a single or group of files is the common use case. Second use case is Antoine’s single change to a large group of files at once. AS of now, I am not convinced we should allow changes across multiple attributes in the same modal experience. Opening that up increases complexity and chance of errors.**
- We can't guarantee that all files selected by the user will have values for the attribute they want to edit, or that the values they do have will be the same 
**So far my understanding is that a user will filter and curate the list of files they want to target carefully and this case won’t happen much. BUT we could always call out file names that don’t include that attribute in the modal for added clarity.**
- We're currently referencing the File Upload App mass edit UI, which only displays a single row that will update values for all selected files, and does not present the current values for the selected files. We're unsure how much we should emulate that interface 
**The FUA is geared toward initial creation of metadata and in FE, it’s more about targeting a single value change to another. This is very infrequent and so far my understanding is that users do not want to overwrite values across many attributes all at one. We do not need to emulate FUA.**

**Comment by lynwilhelm** [comment]
**Design requirements**

As a user that wants to edit metadata for a single or group of selected files I need...

- A way to easily filter to a list of files I would like to select **Q: Can Null values be filtered on in The Finder??? This is important for users to be able to assign values when there are none yet applied.**
- To be able to specify the metadata field I want to target, view what will be replaced and a way to specify a new value for replacement.
- A way to cancel or commit the change
- To have some kind of system success feedback that let’s me know the edit was applied
- To understand what metadata I cannot edit in the Finder and where I can go to do so
- To be able to add a new metadata field and value to a single file or in bulk
- To understand when I’ve selected files that do not currently have that metadata field and a way to either add as new metadata or to exclude
- To understand that editing is destructive and I should be a good steward of metadata by ensuring that what I edit will not create confusion or issues later  

**TBD/needs further definition**
- To be able to view “last edited by” and “last edited date” for each file
Is providing history of edits necessary? What was changed? Is this just for when edited in FMS or also in upload app or Labkey?

**Comment by lynwilhelm** [comment]
Hey, Anya! I assigned this to you but not sure how you want to do this since this is more of a UX ticket than implementation ticket. Here are the final designs for your viewing pleasure:

https://www.figma.com/design/oNQvOAK11YINcbPvNmkgwO/Public-File-Explorer?node-id=875-4724&t=nM3MIpceKUqKI8pl-1
